// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb9AtZ9PiAFB_FhWt_oaObs61yDL5p5A4',
    appId: '1:860611988662:web:5b0af916dbf2606e53aa17',
    messagingSenderId: '860611988662',
    projectId: 'stattrack-7db9f',
    authDomain: 'stattrack-7db9f.firebaseapp.com',
    storageBucket: 'stattrack-7db9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_ZxEJzGahtKh51h9G6tZ1RdsJZhBm-w',
    appId: '1:860611988662:android:ce6e00bcfea00dd053aa17',
    messagingSenderId: '860611988662',
    projectId: 'stattrack-7db9f',
    storageBucket: 'stattrack-7db9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGVNcGFswYSCeBhu3Xg2sLHpyw8cuXyAE',
    appId: '1:860611988662:ios:740b06734f0684f153aa17',
    messagingSenderId: '860611988662',
    projectId: 'stattrack-7db9f',
    storageBucket: 'stattrack-7db9f.appspot.com',
    androidClientId: '860611988662-sqstsnfplctdtqotbfqdl10qkuga2778.apps.googleusercontent.com',
    iosClientId: '860611988662-55gmph2q8lpn2cu5ti3bopq5qfs1o2ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.stattrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGVNcGFswYSCeBhu3Xg2sLHpyw8cuXyAE',
    appId: '1:860611988662:ios:740b06734f0684f153aa17',
    messagingSenderId: '860611988662',
    projectId: 'stattrack-7db9f',
    storageBucket: 'stattrack-7db9f.appspot.com',
    androidClientId: '860611988662-sqstsnfplctdtqotbfqdl10qkuga2778.apps.googleusercontent.com',
    iosClientId: '860611988662-55gmph2q8lpn2cu5ti3bopq5qfs1o2ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.stattrack',
  );
}
